import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, Leaf, Truck, Heart, FlaskConical } from 'lucide-react';
import ProductCard from '@/components/storefront/ProductCard';
import HeroBannerCarousel from '@/components/storefront/HeroBannerCarousel';
import NewsletterForm from '@/components/storefront/NewsletterForm';
import {getCachedFeaturedProducts} from '@/lib/cache';
export const dynamic='force-dynamic';
export const metadata={title:{absolute:'Elavenza Wellness | Botanical rituals for everyday living'},description:'Discover essential oils, carrier oils, skincare and home wellbeing. Find your everyday botanical ritual with Elavenza Wellness.',alternates:{canonical:'/'}};
const categories=[['Essential oils','Little bottles. Beautiful possibilities.','essential-oils'],['Carrier oils','The foundation of your ritual.','carrier-oils'],['Botanical skincare','Make time for your skin.','skincare'],['Home & wellbeing','Bring a little calm home.','wellbeing']];
export default async function Home(){const products=await getCachedFeaturedProducts(4);return <>
<HeroBannerCarousel/>
<div className="values-strip">{[[Leaf,'Inspired by botanicals','/about'],[Truck,'Delivery, made clear','/shipping'],[FlaskConical,'Know your ingredients','/certifications'],[Heart,'Care beyond your order','/faq']].map(([Icon,label,href])=>{const I=Icon as typeof Leaf;return <Link href={href as string} key={label as string}><I size={19}/>{label as string}</Link>})}</div>
<section className="section wrap"><div className="section-heading"><div><p className="eyebrow">YOUR BOTANICAL SHELF</p><h2>Good things grow here.</h2></div><Link href="/products" className="text-link">Shop all collections <ArrowRight size={16}/></Link></div><div className="collection-grid">{categories.map(([name,desc,slug],i)=><Link className="collection-card" href={`/products?category=${slug}`} key={slug}><div className="collection-image"><Image src={`/images/cat-${slug}.jpg`} alt={name} fill sizes="(max-width: 760px) 50vw, 25vw" className="object-cover"/><span>0{i+1}</span></div><h3>{name}<ArrowRight size={18}/></h3><p>{desc}</p></Link>)}</div></section>
<section className="ritual-band"><div className="wrap ritual-inner"><div><p className="eyebrow">HOW DO YOU WANT TO FEEL?</p><h2>There’s a ritual for that.</h2><p>Let a little intention lead the way.</p></div><div className="ritual-links">{[['Unwind','lavender'],['Feel refreshed','eucalyptus'],['Nourish my skin','jojoba'],['Set the mood','diffuser']].map(([label,search])=><Link key={label} href={`/products?search=${search}`}>{label}<ArrowRight size={17}/></Link>)}</div></div></section>
<section className="section wrap"><div className="section-heading"><div><p className="eyebrow">A LOVELY PLACE TO BEGIN</p><h2>Meet your daily essentials.</h2></div><Link className="text-link" href="/products">Explore the range <ArrowRight size={16}/></Link></div>{products.length?<div className="grid grid-cols-2 lg:grid-cols-4 gap-5">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="empty-catalog"><p>Discover your next favourite in our botanical collections.</p><Link className="button" href="/products">Browse the collection <ArrowRight size={16}/></Link></div>}</section>
<section className="story-section wrap"><div className="story-photo"><Image src="/images/cat-skincare.jpg" alt="Botanical skincare with softly lit natural ingredients" fill sizes="(max-width: 760px) 100vw, 50vw" className="object-cover"/></div><div className="story-copy"><p className="eyebrow">THE ELAVENZA PHILOSOPHY</p><h2>Less rush.<br/>More <em>ritual.</em></h2><p>We believe wellbeing belongs in the little moments. The familiar scent that welcomes you home. A few quiet minutes at the end of the day. The simple pleasure of caring for yourself.</p><p>Our collection brings botanicals into those moments, with room to discover what feels right for you.</p><Link className="text-link" href="/about">Get to know Elavenza <ArrowRight size={16}/></Link></div></section>
<section className="section wrap"><div className="section-heading"><div><p className="eyebrow">NOTES FOR SLOWER LIVING</p><h2>The wellness journal.</h2></div><Link href="/journal" className="text-link">Read the journal <ArrowRight size={16}/></Link></div><div className="journal-grid">{[['The art of a Sunday reset','cat-wellbeing','a-sunday-reset'],['The beauty of a simpler skincare shelf','cat-skincare','the-beauty-of-a-simple-shelf'],['A gift with a little thought behind it','cat-essential-oils','a-gift-with-a-little-thought']].map(([title,img,slug])=><Link href={`/journal/${slug}`} key={slug}><div className="journal-image"><Image src={`/images/${img}.jpg`} alt="" fill sizes="(max-width:760px) 100vw, 33vw" className="object-cover"/></div><p className="eyebrow">NOTES FOR SLOWER LIVING</p><h3>{title} <ArrowRight size={17}/></h3></Link>)}</div></section><NewsletterForm/>
</>}
