'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight, MapPin, Package, Plus, ShieldCheck, Trash2, UserRound } from 'lucide-react';
import { getMe, getOrders, type Order, type User } from '@/lib/api';

type Address = { id: number; label: string; recipient_name: string; address_line1: string; address_line2?: string | null; city: string; state: string; postcode: string; country: string; is_default: boolean };
const emptyAddress = { label: 'Home', recipient_name: '', address_line1: '', address_line2: '', city: '', state: '', postcode: '', country: 'Australia', is_default: false };

export default function AccountPage() {
  const router = useRouter();
  const [user, setUser] = useState<User | null>(null); const [orders, setOrders] = useState<Order[]>([]); const [addresses, setAddresses] = useState<Address[]>([]); const [form, setForm] = useState(emptyAddress); const [showForm, setShowForm] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { const stored = localStorage.getItem('elavenza-token'); if (!stored) { router.push('/auth/login?redirect=/account'); return; } Promise.all([getMe(stored), getOrders(stored), fetch('/api/account/addresses', { headers: { Authorization: `Bearer ${stored}` } }).then((r) => r.ok ? r.json() : [])]).then(([me, customerOrders, customerAddresses]) => { setUser(me); setOrders(customerOrders); setAddresses(customerAddresses); }).catch(() => setError('We could not load your account. Please sign in again.')).finally(() => setLoading(false)); }, [router]);
  const saveAddress = async (e: React.FormEvent) => { e.preventDefault(); setError(''); const stored = localStorage.getItem('elavenza-token'); if (!stored) return router.push('/auth/login?redirect=/account'); const response = await fetch('/api/account/addresses', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${stored}` }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) { setError(data.error); return; } setAddresses((current) => [data, ...current]); setForm(emptyAddress); setShowForm(false); };
  const removeAddress = async (id: number) => { await fetch(`/api/account/addresses?id=${id}`, { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }); setAddresses((current) => current.filter((address) => address.id !== id)); };
  const memberSince = useMemo(() => user?.created_at ? new Date(user.created_at).toLocaleDateString('en-AU', { month: 'long', year: 'numeric' }) : '—', [user]);
  if (loading) return <main className="min-h-[70vh] px-4 py-16"><div className="mx-auto max-w-6xl animate-pulse space-y-6"><div className="h-10 w-64 rounded bg-bg-alt" /><div className="h-40 rounded-2xl bg-bg-alt" /></div></main>;
  return <main className="min-h-screen bg-bg px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl space-y-8">
    <header className="flex flex-col justify-between gap-5 border-b border-border pb-8 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">My Elavenza</p><h1 className="mt-2 text-4xl font-heading font-bold text-text">Hello, {user?.first_name || 'there'}.</h1><p className="mt-2 text-text-muted">Your botanical wellness account, all in one place.</p></div><button onClick={() => { localStorage.removeItem('elavenza-token'); localStorage.removeItem('elavenza-user'); window.location.href = '/'; }} className="text-sm font-medium text-text-muted hover:text-primary">Sign out</button></header>
    {error && <div className="rounded-xl border border-error/20 bg-error/10 p-4 text-sm text-error">{error}</div>}
    <section className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-primary p-6 text-white"><p className="text-sm text-white/70">Membership</p><h2 className="mt-2 text-2xl font-heading font-semibold">Botanical Circle</h2><p className="mt-3 text-sm text-white/80">Member since {memberSince}</p><div className="mt-6 flex items-center gap-2 text-sm"><ShieldCheck className="h-4 w-4" /> 10% off every order</div></div><div className="rounded-2xl border border-border bg-surface p-6"><Package className="h-5 w-5 text-primary" /><p className="mt-5 text-sm text-text-muted">Orders placed</p><p className="mt-1 text-3xl font-heading font-semibold text-text">{orders.length}</p></div><div className="rounded-2xl border border-border bg-surface p-6"><MapPin className="h-5 w-5 text-primary" /><p className="mt-5 text-sm text-text-muted">Saved addresses</p><p className="mt-1 text-3xl font-heading font-semibold text-text">{addresses.length}</p></div></section>
    <div className="grid gap-8 lg:grid-cols-[1.35fr_1fr]"><section className="rounded-2xl border border-border bg-surface p-6"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-heading font-semibold text-text">Recent orders</h2><p className="mt-1 text-sm text-text-muted">Track your Elavenza deliveries.</p></div><Package className="h-5 w-5 text-primary" /></div>{orders.length === 0 ? <div className="py-12 text-center"><p className="text-text-muted">Your first order will appear here.</p><Link href="/products" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-primary">Explore botanicals <ArrowRight className="h-4 w-4" /></Link></div> : <div className="mt-6 divide-y divide-border">{orders.slice(0, 5).map((order) => <div key={order.id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-semibold text-text">{order.order_number}</p><p className="mt-1 text-sm text-text-muted">{new Date(order.created_at).toLocaleDateString('en-AU')} · {order.status}</p></div><p className="font-semibold text-text">${Number(order.total).toFixed(2)}</p></div>)}</div>}</section>
    <section className="rounded-2xl border border-border bg-surface p-6"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-heading font-semibold text-text">Saved addresses</h2><p className="mt-1 text-sm text-text-muted">For faster, easier checkout.</p></div><button onClick={() => setShowForm(!showForm)} className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-white"><Plus className="h-4 w-4" /> Add</button></div>{showForm && <form onSubmit={saveAddress} className="mt-5 space-y-3 border-b border-border pb-5">{[['label','Label'],['recipient_name','Full name'],['address_line1','Address'],['city','City'],['state','State'],['postcode','Postcode']].map(([key, label]) => <input key={key} required={key !== 'label'} placeholder={label} value={form[key as keyof typeof form] as string} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="w-full rounded-lg border border-border bg-bg-alt px-3 py-2.5 text-sm outline-none focus:border-primary" />)}<label className="flex items-center gap-2 text-sm text-text-muted"><input type="checkbox" checked={form.is_default} onChange={(e) => setForm({ ...form, is_default: e.target.checked })} /> Make default address</label><button className="w-full rounded-lg bg-primary py-2.5 text-sm font-semibold text-white">Save address</button></form>}{addresses.length === 0 && !showForm ? <div className="py-12 text-center text-sm text-text-muted">No saved addresses yet.</div> : <div className="mt-5 space-y-3">{addresses.map((address) => <div key={address.id} className="flex items-start justify-between gap-3 rounded-xl bg-bg-alt p-4"><div className="flex gap-3"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><div><p className="font-semibold text-text">{address.label} {address.is_default && <span className="ml-1 text-xs font-normal text-primary">Default</span>}</p><p className="mt-1 text-sm leading-6 text-text-muted">{address.recipient_name}<br />{address.address_line1}<br />{address.city}, {address.state} {address.postcode}</p></div></div><button aria-label={`Remove ${address.label} address`} onClick={() => removeAddress(address.id)} className="text-text-light hover:text-error"><Trash2 className="h-4 w-4" /></button></div>)}</div>}</section></div>
    <section className="flex items-center gap-4 rounded-2xl border border-border bg-surface p-5"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-primary"><UserRound className="h-5 w-5" /></div><div><p className="font-semibold text-text">{user?.first_name} {user?.last_name}</p><p className="text-sm text-text-muted">{user?.email}{user?.phone ? ` · ${user.phone}` : ''}</p></div></section>
  </div></main>;
}
