"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowRight, ChevronLeft, ChevronRight, Pause, Play} from 'lucide-react';
const slides=[
 {eyebrow:'ROOTED IN NATURE. MADE FOR YOUR EVERYDAY.',headline:'Come back',prefix:'to ',accent:'yourself.',copy:'Small rituals. Beautiful botanicals. Discover a slower, more intentional way to care for your body, your space, and you.',cta:'Explore the collection',href:'/products',image:'/images/hero-banner.jpg',alt:'Botanical oils and natural textures for a daily wellness ritual',caption:'A moment, just for you.',theme:'sage'},
 {eyebrow:'SOFT SCENTS. SLOWER EVENINGS.',headline:'Let the day',prefix:'',accent:'drift away.',copy:'A familiar floral note. A softer light. Find your favourite botanical companions for the quiet moments at the end of the day.',cta:'Discover essential oils',href:'/products?category=essential-oils',image:'/images/banner-evening.png',alt:'Amber oil bottle with lavender and lilac linen in warm afternoon light',caption:'Your evening, a little softer.',theme:'lilac'},
 {eyebrow:'A LITTLE CARE. A LOVELY RITUAL.',headline:'Make time',prefix:'for ',accent:'your skin.',copy:'Thoughtful textures and botanical favourites. Bring a little intention to your daily skincare ritual, one beautiful moment at a time.',cta:'Explore botanical skincare',href:'/products?category=skincare',image:'/images/banner-skincare.png',alt:'Amber skincare dropper on peach stone with botanical leaves and golden oil',caption:'A little glow in the everyday.',theme:'peach'},
 {eyebrow:'MAKE YOUR SPACE FEEL LIKE YOU.',headline:'A place to',prefix:'',accent:'exhale.',copy:'Set the mood with everyday wellbeing essentials. Turn your favourite corner into a warm welcome, a quiet pause, a moment of home.',cta:'Discover home & wellbeing',href:'/products?category=wellbeing',image:'/images/banner-home.png',alt:'Ceramic diffuser with eucalyptus and lavender linen on a sunlit console',caption:'Good things begin at home.',theme:'sage'}
];
export default function HeroBannerCarousel(){const [index,setIndex]=useState(0);const [paused,setPaused]=useState(false);const [hover,setHover]=useState(false);const [focused,setFocused]=useState(false);const [reduced,setReduced]=useState(true);const touch=useRef<number|null>(null);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>setReduced(media.matches);change();media.addEventListener('change',change);return()=>media.removeEventListener('change',change)},[]);
 useEffect(()=>{if(paused||hover||focused||reduced)return;const timer=setInterval(()=>{if(!document.hidden)setIndex(i=>(i+1)%slides.length)},7000);return()=>clearInterval(timer)},[paused,hover,focused,reduced]);
 function move(direction:number){setIndex(i=>(i+direction+slides.length)%slides.length);setPaused(true)}
 const slide=slides[index];return <section aria-label="Botanical wellness collections" aria-roledescription="carousel" className={`hero-carousel theme-${slide.theme}`} onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)} onFocusCapture={()=>setFocused(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setFocused(false)}} onTouchStart={e=>{touch.current=e.touches[0].clientX}} onTouchEnd={e=>{if(touch.current!==null){const delta=touch.current-e.changedTouches[0].clientX;if(Math.abs(delta)>60)move(delta>0?1:-1);touch.current=null}}}>
 <div className="editorial-hero" aria-roledescription="slide" aria-label={`${index+1} of ${slides.length}`}><div className="hero-copy"><p className="eyebrow">{slide.eyebrow}</p><h1>{slide.headline}<br/>{slide.prefix}<em>{slide.accent}</em></h1><p>{slide.copy}</p><div className="hero-buttons"><Link className="button" href={slide.href}>{slide.cta} <ArrowRight size={17}/></Link><Link className="text-link" href="/ritual-finder">Find your ritual ↗</Link></div><span className="hero-footnote">ELAVENZA / WELLNESS, NATURALLY</span></div><div className="hero-photo"><Image key={slide.image} src={slide.image} alt={slide.alt} fill priority={index===0} sizes="(max-width:760px) 100vw, 55vw" className="object-cover hero-slide-image"/><div className="hero-caption"><span>THE ART OF EVERYDAY WELLNESS</span><p>{slide.caption}</p></div></div></div>
 <div className="carousel-controls"><span className="carousel-count">0{index+1} <span>/ 0{slides.length}</span></span><div className="carousel-dots">{slides.map((s,i)=><button key={s.image} aria-label={`Go to slide ${i+1}: ${s.headline} ${s.accent}`} aria-current={i===index?'true':undefined} onClick={()=>{setIndex(i);setPaused(true)}}><span/></button>)}</div><button className="icon-button" onClick={()=>move(-1)} aria-label="Previous slide"><ChevronLeft size={18}/></button><button className="icon-button" onClick={()=>move(1)} aria-label="Next slide"><ChevronRight size={18}/></button><button className="icon-button" aria-label={paused?'Play slideshow':'Pause slideshow'} onClick={()=>setPaused(!paused)}>{paused?<Play size={15}/>:<Pause size={15}/>}</button></div></section>
}
