"use client";
import {useState,useTransition} from 'react';
import Link from 'next/link';
import {Star} from 'lucide-react';
import {submitReviewAction} from '@/lib/actions';
export default function ReviewForm({slug}:{slug:string}){
 const [rating,setRating]=useState(5);const [message,setMessage]=useState('');const [done,setDone]=useState(false);const [pending,startTransition]=useTransition();
 return <div className="review-form"><p className="eyebrow">YOUR EXPERIENCE MATTERS</p><h3>Share a little of your ritual.</h3><p>Have you tried this botanical? Tell others what you enjoyed. Please <Link href="/auth/login">sign in</Link> before submitting.</p>{!done&&<form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setMessage('');let token='';try{token=localStorage.getItem('elavenza-token')||''}catch{}if(!token){setMessage('Please sign in to your account, then return here to share your review.');return}startTransition(async()=>{try{const result=await submitReviewAction(slug,{rating,title:String(data.get('title')||''),content:String(data.get('content')||'')},token);setMessage(result.message||result.error||'Unable to submit your review.');if(result.success)setDone(true)}catch{setMessage('We couldn’t save your review. Please try again.')}})}}><fieldset disabled={pending}><legend>Your rating</legend><div className="review-rating">{[1,2,3,4,5].map(n=><label key={n}><input type="radio" name="rating" value={n} checked={rating===n} onChange={()=>setRating(n)}/><Star size={25} fill={n<=rating?'currentColor':'none'}/><span className="sr-only">{n} {n===1?'star':'stars'}</span></label>)}</div><label htmlFor="review-title">A few words to sum it up</label><input id="review-title" name="title" required minLength={3} maxLength={120} placeholder="Your review title"/><label htmlFor="review-content">Your experience</label><textarea id="review-content" name="content" required minLength={20} maxLength={2000} rows={5} placeholder="What did you enjoy about this product? (At least 20 characters)"/><button className="button" disabled={pending}>{pending?'Saving your review…':'Share my review →'}</button></fieldset></form>}<p role="status">{message}</p></div>
}
